language: node_js

sudo: required

node_js:
  - "6.9"

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install

script:
  - testrpc &
  - npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/50aa9e70ed5b87727593
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
